### ISSUE TITLE
New Hook causes Render to fire 3 times

### ISSUE THREAD

**Issue by DaleyKD** [wictorwilen/msteams-react-base-component#12] opened 2020-12-09 22:35 UTC
``` jsx
function MyApp(): JSX.Element {
    const [{ inTeams, theme }] = useTeams();

    React.useEffect(() => {
        microsoftTeams.initialize();
        microsoftTeams.appInitialization.notifyAppLoaded();
        microsoftTeams.appInitialization.notifySuccess();
    }, []);

    debugger;

    return (
        <h1>Test</h1>
    );
}

ReactDOM.render(<MyApp />, document.getElementById("root"));
```

Just this simple example causes the debugger to hit 3 times.  Without the new hook (I haven't reverted to v2 to find out), the debugger is hit once.

**Comment by wictorwilen** [comment] 2020-12-10 07:56
@DaleyKD - two things.

1) You're just instantiating the new hook, not using it - what happens if you remove the `const [{inTeams...`. line?
2) You're supposed to use the hook as follows:

``` TypeScript
function MyApp(): JSX.Element {
    const [{ inTeams, theme }] = useTeams();

    React.useEffect(() => {
        if(inTeams) {
            microsoftTeams.appInitialization.notifyAppLoaded();
            microsoftTeams.appInitialization.notifySuccess();
        }
    }, [inTeams]);

    debugger;

    return (
        <h1>Test</h1>
    );
}

ReactDOM.render(<MyApp />, document.getElementById("root"));
```

**Comment by DaleyKD** [comment] 2020-12-10 15:28
Thanks, Wictor.  I was trying to reduce the code to see what happened (should have been a bit more verbose).  So here's the results of your questions:

1. If I remove the usage of the hook, then it's hit once, as expected.
```jsx
import React from "react";
import ReactDOM from "react-dom";

import { useTeams } from "msteams-react-base-component";
import * as microsoftTeams from "@microsoft/teams-js";

function MyApp() {
    //const [{ inTeams }] = useTeams();

    React.useEffect(() => {
        console.log(`In the Effect. inTeams: does not exist`);
        //if (inTeams) {
        //    microsoftTeams.appInitialization.notifyAppLoaded();
        //    microsoftTeams.appInitialization.notifySuccess();
        //}
    }, []);//[inTeams]);

    console.log("MyApp Re-Render! - We don't want to get here too often.");

    return (
        <h1>Test</h1>
    );
}

ReactDOM.render(<MyApp />, document.getElementById("root"));
```
![image](https://user-images.githubusercontent.com/7206282/101791913-b2f26680-3ac9-11eb-82f1-e92bdb302668.png)


2. If I do that exact snippet, `debugger;` is hit 6 times (confirmed in production mode, too).
``` jsx
import React from "react";
import ReactDOM from "react-dom";

import { useTeams } from "msteams-react-base-component";
import * as microsoftTeams from "@microsoft/teams-js";

function MyApp() {
    const [{ inTeams }] = useTeams();

    React.useEffect(() => {
        console.log(`In the Effect. inTeams: ${inTeams}`);
        if (inTeams) {
            microsoftTeams.appInitialization.notifyAppLoaded();
            microsoftTeams.appInitialization.notifySuccess();
        }
    }, [inTeams]);

    console.log("MyApp Re-Render! - We don't want to get here too often.");

    return (
        <h1>Test</h1>
    );
}

ReactDOM.render(<MyApp />, document.getElementById("root"));
```
This small snippet produces the following in the console:
![image](https://user-images.githubusercontent.com/7206282/101790662-5478b880-3ac8-11eb-83ae-b6e170df04b7.png)

**Comment by wictorwilen** [comment] 2020-12-10 16:05
Thanks, I can confirm this behavior. It's partially due to React not batching state changes since we're using callbacks. Working on a fix to find the minimum amount of state changes.

**Comment by wictorwilen** [comment] 2020-12-10 16:25
I'm down to two renders now by forcing batching and some other tweaks...requires some more testing before publishing a preview! Thanks again for raising this issue

**Comment by wictorwilen** [comment] 2020-12-11 08:41
@DaleyKD - would you mind testing the just released preview (`npm install msteams-react-base-component@3.0.1-preview`. This one should give you three re-renders. 1) first time, 2) when the initial theme is  set, 3) when the Teams context is initialized or not

**Comment by wictorwilen** [comment] 2020-12-13 10:42
Thanks for all the encouragement! I'll close this once I publish the non preview version. I'd like to explore the production scenario you mention above.

**Comment by DaleyKD** [comment] 2020-12-22 20:55
I'll try to get you something a bit more concrete.  It's harder to simulate/codesandbox, because I'm PRETTY sure the extra render is because of the OIDC stuff.

**Comment by wictorwilen** [comment] 2021-03-01 17:36
Added unit tests to verify that it only runs three times (as intended right now), in #18. Will look into further optimizations going forward

**Closed by wictorwilen** 2021-03-01 17:36 UTC
Labels: bug
